<?php

use Drupal\Core\Render\Element;
use Drupal\Core\Url;


/**
 * @file
 * Implements hook_theme().
 */
function rgb_theme($existing, $type, $theme, $path): array
{
  return [
    'guest-page' => [
      'variables' => [
        'form' => NULL,
        'reviews' => NULL,
        'pager' => NULL,
      ],
    ],
    'rgb' => [
      'template' => 'rgb',
      'render element' => 'elements',
    ]
  ];
}
/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_rgb(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];

  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  /** @var \Drupal\rgb\Entity\RgbEntity $entity */
  $entity = $variables['elements']['#rgb'];

  // Add control button.
  $variables['button'] = [
    '#type' => 'link',
    '#title' => 'Manage',
    '#url' => Url::fromRoute('entity.rgb.edit', ['rgb' => $entity->id()],),
  ];

  // Add default image.
  if (count($variables['content']['avatar']) <= 3) {
    $variables['content']['avatar'] = [
      '#theme' => 'image',
      '#uri' => '/modules/custom/rgb/files/user-icon.jpg',
      '#attributes' => [
        'alt' => 'picture',
        'width' => 100,
        'height' => 100,
      ],
    ];
  }

  $variables['#attached']['library'][] = 'rgb/rgb.reviews';

}
